repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2  # 最新版を確認して指定（ https://github.com/astral-sh/ruff-pre-commit/releases ）
    hooks:
      - id: ruff
      - id: ruff-format